import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ui/theme-provider";
import BackgroundMeteors from "@/components/ui/backgroundmeteors";
import { Onest } from "next/font/google";
import "./globals.css";

// Import Google Fonts với className để tránh mismatch
const geistSans = Onest({
  subsets: ["latin"],
  variable: "--font-onest-sans", // vẫn khai báo variable nếu cần
});

const geistMono = Onest({
  subsets: ["latin"],
  variable: "--font-onest-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* Sử dụng className thay vì variable */}
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <BackgroundMeteors>{children}</BackgroundMeteors>
        </ThemeProvider>
      </body>
    </html>
  );
}
